# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Rambling Raconteur
email: behemphi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Practical stories for key DevOps concepts
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://behemphi.github.io" # the base hostname & protocol for your site
twitter_username: behemphi  
github_username:  behemphi

# Build settings
markdown: kramdown
