# Site settings
title: DevOpsery
email: behemphi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, musings and some occasional reasoning about DevOps practices.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://behemphi.github.io" # the base hostname & protocol for your site
twitter_username: behemphi
github_username: behemphi

# Build settings
markdown: kramdown
