jekyll_runtime:
  image: "jekyll/jekyll:pages"
  environment:
    - POLLING=true
  container_name: jekyll_runtime
  tty: true
  ports:
    - "$JEKYLL_RUNTIME_IP:4000:4000/tcp"
  volumes:
    - ".:/srv/jekyll"
